### ISSUE TITLE
Which should be our default model?

### ISSUE THREAD

**Issue by carmocca** [Lightning-AI/lit-stablelm#14]
Given that this repository supports a multitude of models, which one should be chosen when the user doesn't specify it?

This is important because in the howtos and README, concrete numbers are given for a model

Alternatively, should we force the user to choose one?

**Comment by ArturK-85** [comment]
3B model, since larger models are available in lit-llama, it would be good for this repository to focus on a smaller model to make it available to more researchers and egde devices

**Comment by carmocca** [comment]
Sounds good. We'll use `stabilityai/stablelm-base-alpha-3b`

Leaving this issue open until we've updated the memory requirements for it in our docs
